[package]
name = "objtr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
eframe = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
rayon = "1.10.0"
rfd = "0.14.1"
serde = {version = "1.0.210",  features = ["derive"]}
serde-xml-rs = "0.6.0"
walkdir = "2.5.0"
